//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushPull.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PushPull.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new task.
        /// </summary>
        public static string AddNewTask {
            get {
                return ResourceManager.GetString("AddNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be longer than 50 characters.
        /// </summary>
        public static string CommonStringMaxLength {
            get {
                return ResourceManager.GetString("CommonStringMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be longer than 200 characters.
        /// </summary>
        public static string ContentMaxLength {
            get {
                return ResourceManager.GetString("ContentMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline can only be today or after.
        /// </summary>
        public static string DateLargerThanToday {
            get {
                return ResourceManager.GetString("DateLargerThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EisenHower type.
        /// </summary>
        public static string EisenHowerType {
            get {
                return ResourceManager.GetString("EisenHowerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important but not urgent.
        /// </summary>
        public static string EisenHowerType_INU {
            get {
                return ResourceManager.GetString("EisenHowerType_INU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important and urgent.
        /// </summary>
        public static string EisenHowerType_IU {
            get {
                return ResourceManager.GetString("EisenHowerType_IU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not important and not urgent.
        /// </summary>
        public static string EisenHowerType_NINU {
            get {
                return ResourceManager.GetString("EisenHowerType_NINU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not important but urgent.
        /// </summary>
        public static string EisenHowerType_NIU {
            get {
                return ResourceManager.GetString("EisenHowerType_NIU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail value.
        /// </summary>
        public static string FailValue {
            get {
                return ResourceManager.GetString("FailValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Asset.
        /// </summary>
        public static string MoneyAsset {
            get {
                return ResourceManager.GetString("MoneyAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull asset.
        /// </summary>
        public static string PullAssetValue {
            get {
                return ResourceManager.GetString("PullAssetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push asset.
        /// </summary>
        public static string PushAssetValue {
            get {
                return ResourceManager.GetString("PushAssetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success value.
        /// </summary>
        public static string SuccessValue {
            get {
                return ResourceManager.GetString("SuccessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Asset.
        /// </summary>
        public static string TimeAsset {
            get {
                return ResourceManager.GetString("TimeAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value type.
        /// </summary>
        public static string ValueType {
            get {
                return ResourceManager.GetString("ValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value unit.
        /// </summary>
        public static string ValueUnit {
            get {
                return ResourceManager.GetString("ValueUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
    }
}
